
services:
  postgres:
    image: postgres:16
    container_name: gthdf-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gthdf
      POSTGRES_USER: gthdf
      POSTGRES_PASSWORD: gthdf
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: gthdf-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    environment:
      MINIO_ROOT_USER: gthdf
      MINIO_ROOT_PASSWORD: gthdfpassword
    volumes:
      - miniodata:/data

  strapi:
    image: node:24-alpine
    container_name: gthdf-strapi
    restart: unless-stopped
    working_dir: /app
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --max-old-space-size=2048
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: gthdf
      DATABASE_USERNAME: gthdf
      DATABASE_PASSWORD: gthdf
      DATABASE_SSL: false
      AWS_ACCESS_KEY_ID: gthdf
      AWS_SECRET_ACCESS_KEY: gthdfpassword
      AWS_REGION: us-east-1
      AWS_ENDPOINT: http://minio:9000
      AWS_BUCKET: gthdf-media
      AWS_CDN_URL: http://127.0.0.1:9000/gthdf-media
      APP_KEYS: Q0T9u38qvke3tRvDZnO+8A==,7kM0OTH1SXj6Z0xPRZ6ZBg==,DsF2rBuQruBEPEhuI6zl5A==,1CDKU3+3ulhYsxKfQYlaRA==
      API_TOKEN_SALT: HQI2p+kY9oy74YLZcjpOSg==
      ADMIN_JWT_SECRET: 0DTOsjZ5dFNCWLbANj5BTg==
      TRANSFER_TOKEN_SALT: qnjAyEz3RMBoSQjdzWQ9IA==
      ENCRYPTION_KEY: Fp0Sx6n8uYeZrJBme++tMg==
      JWT_SECRET: 1oxJOhFnpvM9x9Lm/GfEYA==
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - minio
    command: npm run develop

volumes:
  pgdata:
  miniodata:
